### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by stmoerman** [dannystey/grav-plugin-instagram-feed#5]
Haven't looked into what causes it, but your plugin seems to need an update after the most recent Grav updates.

`
Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("Undefined property: stdClass::$user")."
`

**Comment by ghost** [comment]
I've updated my Grav website myself today and noticed the error is happening at the section that parses the json data, more specifically `if($data->user->username == $this->username) {`

Haven't written a quick fix yet.

**Comment by ricardo118** [comment]
Hi, I noticed the same bug today on my website (although I hadn't updated grav) it seems like it was a change from instagram themselves. I've submitted a fix for it, it's working again on my website currently

**Comment by dannystey** [comment]
merged ricardo118 fix. thanks for your support
