### ISSUE TITLE
Just noticed "Could not load the Instagram feed!" on two sites using this plugin?

### ISSUE THREAD

**Issue by MattAppleton** [dannystey/grav-plugin-instagram-feed#7]
After implementing the API edit at the end of last year, instagram feed was working perfectly on these two sites but just recently the 'Could not load...' message has been coming up.

http://www.florenciadurante.com
http://ciadurante.com

Has anything changed on the Instagram side (again?!)

**Comment by ricardo118** [comment]
yeah i fixed it on a pr, instagram changed things. the owner hasnt pulled but its working on my project

**Comment by MattAppleton** [comment]
Will have a look thanks for the heads up!
