### ISSUE TITLE
Gathering data from instagram using url https://www.instagram.com/username/?__a=1 doesnt work anymore.

### ISSUE THREAD

**Issue by kimkil94** [dannystey/grav-plugin-instagram-feed#8]
Instagram disabled this option to get data in JSON format. Currently receiving 403 response.

**Comment by dannystey** [comment]
ok i guess instagram closed this inoffical leak completly ... therefore i have to reference you to the other instagram plugin with access token https://github.com/artifex404/grav-plugin-instagram
